CREATE INDEX MyObject2WTPartLink$COMPOSIT0 ON MyObject2WTPartLink(idA3A5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
CREATE INDEX MyObject2WTPartLink$COMPOSIT1 ON MyObject2WTPartLink(idA3B5)
 TABLESPACE INDX
 STORAGE ( INITIAL 20k NEXT 20k PCTINCREASE 0 )
/
